FROM busybox                                                                                                                 
WORKDIR /home                                                                              
# RUN: gets exicuted when building the image file                                                                                              
CMD ["echo", "this docker works."]
